module.exports = [
  { id: 'p1', name: 'Classic Canvas Tote', category: 'Accessories', price: 38, compareAt: null, image: 'tote', blurb: 'Heavyweight cotton canvas, reinforced straps, room for everything.', description: 'Our best-selling tote is cut from 16oz heavyweight cotton canvas and finished with bar-tacked straps that won\'t give out. An interior pocket keeps your phone and keys from disappearing into the void.', rating: 4.8, reviews: 212, stock: 34 },
  { id: 'p2', name: 'Merino Wool Sweater', category: 'Apparel', price: 89, compareAt: 120, image: 'sweater', blurb: 'Temperature-regulating merino, zero itch, all season.', description: 'Knit from 100% extra-fine merino wool that regulates temperature and resists odor — wear it on a plane, on a hike, or to dinner. Pre-washed so it keeps its shape wash after wash.', rating: 4.9, reviews: 341, stock: 18 },
  { id: 'p3', name: 'Minimalist Desk Lamp', category: 'Home', price: 64, compareAt: null, image: 'lamp', blurb: 'Warm, dimmable LED on a weighted aluminum base.', description: 'A dimmable 2700K LED housed in brushed aluminum, with a weighted base that won\'t tip. Touch-sensitive dimmer, no buttons, no fuss.', rating: 4.6, reviews: 98, stock: 52 },
  { id: 'p4', name: 'Wireless Earbuds Pro', category: 'Tech', price: 129, compareAt: 159, image: 'earbuds', blurb: 'Active noise cancellation, 30hr battery with the case.', description: 'Active noise cancellation tuned for daily commutes, with a 30-hour total battery life including the charging case. IPX4 water resistance for runs in the rain.', rating: 4.7, reviews: 503, stock: 61 },
  { id: 'p5', name: 'Leather Weekender Bag', category: 'Accessories', price: 210, compareAt: null, image: 'weekender', blurb: 'Full-grain leather that gets better with every trip.', description: 'Hand-cut from full-grain leather that develops a richer patina with every trip. Fits under most airline seats and has a dedicated shoe compartment.', rating: 4.9, reviews: 76, stock: 9 },
  { id: 'p6', name: 'Ceramic Pour-Over Set', category: 'Home', price: 42, compareAt: null, image: 'pourover', blurb: 'Hand-glazed dripper, server, and reusable filter.', description: 'A hand-glazed ceramic dripper and matching server, paired with a reusable stainless filter so you never buy paper filters again.', rating: 4.5, reviews: 134, stock: 27 },
  { id: 'p7', name: 'Organic Cotton Tee', category: 'Apparel', price: 28, compareAt: 36, image: 'tee', blurb: 'GOTS-certified cotton, cut for a modern fit.', description: 'A heavyweight tee in GOTS-certified organic cotton, garment-dyed for a lived-in feel from the first wear. Cut slightly boxy for a modern fit.', rating: 4.7, reviews: 288, stock: 73 },
  { id: 'p8', name: 'Smart Fitness Band', category: 'Tech', price: 79, compareAt: null, image: 'fitband', blurb: 'Sleep tracking, heart rate, and a 10-day battery.', description: 'Tracks sleep stages, resting heart rate, and workouts automatically, all on a battery that lasts up to 10 days per charge. Swim-proof to 50m.', rating: 4.4, reviews: 167, stock: 44 },
  { id: 'p9', name: 'Linen Throw Blanket', category: 'Home', price: 56, compareAt: null, image: 'blanket', blurb: 'Stonewashed European linen, softer with every wash.', description: 'Stonewashed European linen in a generous 130x180cm size — gets softer with every wash and looks equally at home on a bed or sofa.', rating: 4.8, reviews: 59, stock: 21 },
  { id: 'p10', name: 'Aviator Sunglasses', category: 'Accessories', price: 95, compareAt: 115, image: 'sunglasses', blurb: 'Polarized glass lenses, hand-finished acetate frame.', description: 'Polarized glass lenses cut glare without distorting color, set in a hand-finished acetate frame. Comes with a hard case and microfiber cloth.', rating: 4.6, reviews: 143, stock: 38 },
];
